apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: IpPoolCalico
spec:
  cidr: 192.168.131.101/24
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: all()
  allowedUses:
    - Workload
    - Tunnel